server:
  port: 1000
spring:
  application:
    name: gateway
  cloud:
    nacos:
      config:
        server-addr: 192.168.50.6:8849
        group: DEFAULT_GROUP
        file-extension: yml
        import-check:
          enabled: false
      discovery:
        server-addr: 192.168.50.6:8849
      username: nacos
      password: nacos
    gateway:
      routes:
        - id: auth-router
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - PasswordDecoderFilter
            - ValidateCodeFilter
        - id: ujms-router
          uri: lb://biz
          predicates:
            - Path=/biz/**
      encode-key: 'abcdefgabcabcdef'
      ignore-clients:
        - test
