server:
  port: 1000
spring:
  application:
    name: gateway
  cloud:
    nacos:
      config:
        server-addr: 192.168.50.6:8849
        group: DEFAULT_GROUP
        file-extension: yml
        import-check:
          enabled: false
      discovery:
        server-addr: 192.168.50.6:8849
      username: nacos
      password: nacos
    gateway:
      httpclient:
        pool:
          max-idle-time: 1000
      routes:
        - id: auth-router-login
          uri: lb://auth
          predicates:
            - Path=/auth/oauth2/token
          filters:
            - AddRequestHeader=Authorization, Basic Y2xpZW50OjEyMzQ=
            - PasswordDecoderFilter
            - ValidateCodeFilter
#            - AddRequestParameter=client_id, client
#            - AddRequestParameter=client_secret, 1234
#            - AddRequestHeader=Authorization, Basic Y2xpZW50OjEyMzQ=
#            - RewritePath=/auth/login(?<segment>.*), /auth/oauth2/token$\{segment}
        - id: auth-router-logout
          uri: lb://auth
          predicates:
            - Path=/auth/token/logout
        - id: ujms-router
          uri: lb://biz
          predicates:
            - Path=/biz/**
      encode-key: 'abcdefgabcabcdef'
      ignore-clients:
        - test
