server:
  port: 1001
spring:
  application:
    name: auth
  cloud:
    nacos:
      config:
        server-addr: 172.25.41.181:8848
        group: DEFAULT_GROUP
        file-extension: yml
        import-check:
          enabled: false
      discovery:
        server-addr: 172.25.41.181:8848
      username: nacos
      password: nacos

logging:
  level:
    org.springframework.security: TRACE