server:
  port: 1001
spring:
  application:
    name: auth
  cloud:
    nacos:
      config:
        server-addr: 192.168.50.6:8849
        group: DEFAULT_GROUP
        file-extension: yml
        import-check:
          enabled: false
      discovery:
        server-addr: 192.168.50.6:8849
      username: nacos
      password: nacos

logging:
  level:
    org.springframework.security: TRACE