spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/local
  redis:
    host: 39.106.166.224
    password: 123456
    port: 29553
    database: 3
  profiles:
    include: config

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  configuration:
    cache-enabled: false
    jdbc-type-for-null: 'null'
    # log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-underline: true
      insert-strategy: not_empty
      update-strategy: not_empty
  type-handlers-package: 'com.jo.common.mybatis.handler'