server:
  port: 1002
spring:
  application:
    name: biz
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/local
  cloud:
    nacos:
      config:
        server-addr: 192.168.50.6:8849
        group: DEFAULT_GROUP
        file-extension: yml
      discovery:
        server-addr: 192.168.50.6:8849
      username: nacos
      password: nacos
  config:
    import:
      - nacos:application.yml
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  configuration:
    cache-enabled: false
    jdbc-type-for-null: 'null'
    # log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-underline: true
      insert-strategy: not_empty
      update-strategy: not_empty
  type-handlers-package: 'com.jo.common.mybatis.handler'