server:
  port: 1002
spring:
  application:
    name: biz
  cloud:
    nacos:
      config:
        server-addr: 172.25.41.181:8848
        group: DEFAULT_GROUP
        file-extension: yml
        import-check:
          enabled: false
      discovery:
        server-addr: 172.25.41.181:8848
      username: nacos
      password: nacos